-- Webhook de entrega invoice.ready: tablas, paquetes, ORDS y VPD.
PROMPT === client_webhook_endpoint + document_webhook_delivery ===

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE client_webhook_endpoint (
      client_id         NUMBER NOT NULL,
      environment       VARCHAR2(4) NOT NULL,
      url               VARCHAR2(500),
      secret_ciphertext BLOB,
      secret_nonce      RAW(16),
      key_version       NUMBER DEFAULT 1 NOT NULL,
      is_active         NUMBER(1) DEFAULT 0 NOT NULL,
      updated_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT pk_client_webhook PRIMARY KEY (client_id, environment),
      CONSTRAINT fk_webhook_client FOREIGN KEY (client_id) REFERENCES client (id_client) ON DELETE CASCADE,
      CONSTRAINT ck_webhook_env CHECK (environment IN ('TEST', 'PROD')),
      CONSTRAINT ck_webhook_active CHECK (is_active IN (0, 1))
    )]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE document_webhook_delivery (
      id_delivery      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      client_id        NUMBER NOT NULL,
      document_id      NUMBER NOT NULL,
      cdc              VARCHAR2(44) NOT NULL,
      environment      VARCHAR2(4) NOT NULL,
      event_type       VARCHAR2(40) NOT NULL,
      event_id         VARCHAR2(80) NOT NULL,
      delivery_uuid    VARCHAR2(64) NOT NULL,
      target_url       VARCHAR2(500),
      status           VARCHAR2(20) NOT NULL,
      attempts         NUMBER DEFAULT 0 NOT NULL,
      max_attempts     NUMBER DEFAULT 10 NOT NULL,
      lease_owner      VARCHAR2(64),
      lease_until      TIMESTAMP(6) WITH TIME ZONE,
      last_http_status NUMBER,
      last_error       VARCHAR2(2000),
      delivered_at     TIMESTAMP(6) WITH TIME ZONE,
      created_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT fk_whd_client FOREIGN KEY (client_id) REFERENCES client (id_client) ON DELETE CASCADE,
      CONSTRAINT fk_whd_doc FOREIGN KEY (document_id) REFERENCES document (id_document) ON DELETE CASCADE,
      CONSTRAINT uq_whd_doc_event UNIQUE (document_id, event_type),
      CONSTRAINT uq_whd_event_id UNIQUE (event_id),
      CONSTRAINT uq_whd_delivery_uuid UNIQUE (delivery_uuid),
      CONSTRAINT ck_whd_env CHECK (environment IN ('TEST', 'PROD')),
      CONSTRAINT ck_whd_status CHECK (status IN ('PENDING', 'PROCESSING', 'DELIVERED', 'FAILED'))
    )]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_whd_claim ON document_webhook_delivery (status, lease_until, created_at)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_whd_client_cdc ON document_webhook_delivery (client_id, cdc)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

@@../packages/PKG_ESIGN_WEBHOOK_API.sql
@@../packages/PKG_ESIGN_WEBHOOK_DELIVERY_API.sql

PROMPT === Recompilar PKG_ESIGN_CLIENT_API (webhook en context) ===
@@../packages/PKG_ESIGN_CLIENT_API.sql

PROMPT === VPD: agregar tablas webhook ===
@@../policies/03_apply_policies.sql

PROMPT === ORDS panel + interno webhook ===
@@../ords/03_esign_webhook_ords.sql

PROMPT === Migración webhook finalizada ===
