-- Metadatos verificables del XML firmado + cola durable de KuDE.
-- Idempotente. No publica XML en Object Storage.
PROMPT === document_xml metadatos ===

DECLARE
  PROCEDURE add_col(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -1430 THEN NULL; -- column already exists
      ELSE RAISE;
      END IF;
  END add_col;
BEGIN
  add_col('ALTER TABLE document_xml ADD (xml_sha256 VARCHAR2(64))');
  add_col('ALTER TABLE document_xml ADD (xml_size_bytes NUMBER)');
  add_col('ALTER TABLE document_xml ADD (xml_mime_type VARCHAR2(100) DEFAULT ''application/xml; charset=UTF-8'')');
  add_col('ALTER TABLE document_xml ADD (xml_captured_at TIMESTAMP(6) WITH TIME ZONE)');
  add_col('ALTER TABLE document_xml ADD (xml_availability VARCHAR2(20) DEFAULT ''MISSING'')');
END;
/
BEGIN
  EXECUTE IMMEDIATE q'[
    ALTER TABLE document_xml ADD CONSTRAINT ck_document_xml_avail
      CHECK (xml_availability IN ('MISSING', 'AVAILABLE', 'CORRUPT'))
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-2260, -2264) THEN NULL; -- name/constraint exists
    ELSE RAISE;
    END IF;
END;
/

-- Backfill: filas con XML existente pasan a AVAILABLE (hash se completa al re-registrar).
UPDATE /*+ no_parallel */ document_xml
   SET xml_availability = 'AVAILABLE',
       xml_mime_type = NVL(xml_mime_type, 'application/xml; charset=UTF-8'),
       xml_captured_at = NVL(xml_captured_at, SYSTIMESTAMP),
       xml_size_bytes = NVL(xml_size_bytes, DBMS_LOB.GETLENGTH(xml_firmado))
 WHERE xml_firmado IS NOT NULL
   AND NVL(xml_availability, 'MISSING') = 'MISSING';

COMMENT ON COLUMN document_xml.xml_sha256 IS 'SHA-256 hex del XML firmado canónico (bytes UTF-8).';
COMMENT ON COLUMN document_xml.xml_availability IS 'MISSING=sin CLOB; AVAILABLE=CLOB+hash; CORRUPT=inconsistente.';

PROMPT === document_kude_task ===

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM user_tables WHERE table_name = 'DOCUMENT_KUDE_TASK';
  IF l_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE document_kude_task (
        id_task       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        client_id     NUMBER NOT NULL,
        document_id   NUMBER NOT NULL,
        cdc           VARCHAR2(44) NOT NULL,
        status        VARCHAR2(20) NOT NULL,
        attempts      NUMBER DEFAULT 0 NOT NULL,
        max_attempts  NUMBER DEFAULT 10 NOT NULL,
        lease_owner   VARCHAR2(64),
        lease_until   TIMESTAMP(6) WITH TIME ZONE,
        payload_json  CLOB,
        last_error    VARCHAR2(2000),
        created_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
        completed_at  TIMESTAMP(6) WITH TIME ZONE,
        CONSTRAINT fk_kude_task_client FOREIGN KEY (client_id) REFERENCES client (id_client) ON DELETE CASCADE,
        CONSTRAINT fk_kude_task_doc    FOREIGN KEY (document_id) REFERENCES document (id_document) ON DELETE CASCADE,
        CONSTRAINT uq_kude_task_doc    UNIQUE (document_id),
        CONSTRAINT ck_kude_task_status CHECK (status IN ('PENDING', 'PROCESSING', 'READY', 'FAILED'))
      )
    ]';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_kude_task_claim ON document_kude_task (status, lease_until, created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ix_kude_task_cdc ON document_kude_task (client_id, cdc)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

COMMENT ON TABLE document_kude_task IS
  'Cola durable KuDE: lease + intentos; payload = KudeData JSON. XML no se publica en bucket.';

BEGIN
  dbms_rls.drop_policy(
    object_schema => sys_context('userenv', 'current_schema'),
    object_name   => 'DOCUMENT_KUDE_TASK',
    policy_name   => 'VPD_DOCUMENT_KUDE_TASK'
  );
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  dbms_rls.add_policy(
    object_schema   => sys_context('userenv', 'current_schema'),
    object_name     => 'DOCUMENT_KUDE_TASK',
    policy_name     => 'VPD_DOCUMENT_KUDE_TASK',
    function_schema => sys_context('userenv', 'current_schema'),
    policy_function => 'FN_TENANT_POLICY',
    statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check    => TRUE
  );
END;
/

COMMIT;
PROMPT === OK: document_xml artifacts + document_kude_task ===
