-- users: PERSONA que hace login en el panel. CERO informacion financiera / SIFEN.
-- El aislamiento multi-tenant NO gira alrededor del usuario sino del client (negocio).
CREATE TABLE users (
  id_user           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email             VARCHAR2(150) NOT NULL,
  password_hash     VARCHAR2(255) NOT NULL,
  password_salt     VARCHAR2(64)  NOT NULL,
  first_name        VARCHAR2(50),
  last_name         VARCHAR2(50),
  is_active         NUMBER(1) DEFAULT 0 NOT NULL,
  email_verified_at TIMESTAMP(6) WITH TIME ZONE,
  created_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_users_email    UNIQUE (email),
  CONSTRAINT ck_users_active   CHECK (is_active IN (0,1))
);

COMMENT ON TABLE  users IS 'Persona fisica que hace login. Sin datos financieros/SIFEN (esos cuelgan de client).';
COMMENT ON COLUMN users.password_hash IS 'Hash PBKDF2/SHA-512 con salt por usuario (PKG_ESIGN_UTIL).';
COMMENT ON COLUMN users.password_salt IS 'Salt por usuario (defensa contra rainbow tables).';
