-- client: NEGOCIO / CUENTA = entidad legal. Eje de TODA la VPD (id_client).
-- Las API keys y el certificado .p12 pertenecen al CLIENTE, nunca al usuario.
-- El certificado y el password del P12 se guardan cifrados (AES-256-GCM hecho en Go):
-- Oracle solo ve ciphertext + nonce, nunca el claro.
CREATE TABLE client (
  id_client            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_name        VARCHAR2(255) NOT NULL,          -- Razon Social
  ruc                  VARCHAR2(15)  NOT NULL,
  dv                   NUMBER(1),
  status               VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,  -- ACTIVE | SUSPENDED | INACTIVE
  -- API keys: se guarda HASH + prefijo visible; la key completa se muestra 1 sola vez (patron Stripe).
  sk_test_prefix       VARCHAR2(24),
  sk_test_hash         VARCHAR2(128),
  sk_test_status       VARCHAR2(20),                    -- ACTIVE | REVOKED
  sk_prod_prefix       VARCHAR2(24),
  sk_prod_hash         VARCHAR2(128),
  sk_prod_status       VARCHAR2(20),
  -- Certificado .p12 cifrado en Go (AES-256-GCM); Oracle nunca ve el claro.
  cert_subject_dn      VARCHAR2(400),
  cert_not_after       TIMESTAMP(6) WITH TIME ZONE,
  cert_p12_ciphertext  BLOB,
  cert_p12_nonce       RAW(16),
  cert_pwd_ciphertext  BLOB,
  cert_pwd_nonce       RAW(16),
  cert_key_version     NUMBER DEFAULT 1,
  cert_status          VARCHAR2(20),                    -- ACTIVE | EXPIRED | NONE
  created_at           TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_client_sk_test UNIQUE (sk_test_hash),
  CONSTRAINT uq_client_sk_prod UNIQUE (sk_prod_hash),
  CONSTRAINT ck_client_status  CHECK (status IN ('ACTIVE','SUSPENDED','INACTIVE'))
);

COMMENT ON TABLE  client IS 'Negocio/cuenta = entidad legal. Eje de la VPD (id_client). Dueno de API keys y certificado cifrado.';
COMMENT ON COLUMN client.sk_test_hash        IS 'Hash de la API key de TEST (sk_test_...). La key completa se muestra 1 sola vez.';
COMMENT ON COLUMN client.sk_prod_hash        IS 'Hash de la API key de PROD (sk_prod_...).';
COMMENT ON COLUMN client.cert_p12_ciphertext IS 'P12 cifrado AES-256-GCM (clave maestra en Go). Oracle nunca ve el claro.';
COMMENT ON COLUMN client.cert_key_version    IS 'Version de la clave maestra usada para cifrar (rotacion).';
