-- client_user: MEMBRESIA que conecta personas (users) con negocios (client) y define
-- el rol. Un mismo email puede ser dueno de varios negocios o invitado al panel de un
-- tercero (modelo de invitaciones tipo Stripe).
--   owner     : gestiona todo (identidad, keys, certificado, emision).
--   developer : ve/rota API keys y emite; no gestiona identidad fiscal.
--   analyst   : SOLO lee documentos; 403 en certificado y API keys.
CREATE TABLE client_user (
  id_client_user NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id      NUMBER NOT NULL,
  user_id        NUMBER NOT NULL,
  role           VARCHAR2(20) NOT NULL,
  is_active      NUMBER(1) DEFAULT 1 NOT NULL,
  created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_client_user_client FOREIGN KEY (client_id) REFERENCES client (id_client) ON DELETE CASCADE,
  CONSTRAINT fk_client_user_user   FOREIGN KEY (user_id)   REFERENCES users  (id_user),
  CONSTRAINT uq_client_user        UNIQUE (client_id, user_id),
  CONSTRAINT ck_client_user_role   CHECK (role IN ('owner','developer','analyst')),
  CONSTRAINT ck_client_user_active CHECK (is_active IN (0,1))
);

CREATE INDEX ix_client_user_user ON client_user (user_id);

COMMENT ON TABLE  client_user IS 'Membresia persona<->negocio con rol (owner|developer|analyst).';
COMMENT ON COLUMN client_user.role IS 'owner: todo; developer: keys+emision; analyst: solo lectura de documentos.';
