-- user_session: refresh tokens atados a la membresia (client + user). El JWT de acceso
-- lleva el client_id/role elegido; el refresh permite renovar sin volver a loguear.
CREATE TABLE user_session (
  id_user_session NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_user_id  NUMBER NOT NULL,
  refresh_token   VARCHAR2(200) NOT NULL,
  expires_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  is_revoked      NUMBER(1) DEFAULT 0 NOT NULL,
  created_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_user_session_cu   FOREIGN KEY (client_user_id) REFERENCES client_user (id_client_user) ON DELETE CASCADE,
  CONSTRAINT uq_user_session_rt   UNIQUE (refresh_token),
  CONSTRAINT ck_user_session_rev  CHECK (is_revoked IN (0,1))
);

CREATE INDEX ix_user_session_cu ON user_session (client_user_id);

COMMENT ON TABLE user_session IS 'Refresh tokens del panel, atados a la membresia client_user.';
