-- client_emisor: identidad fiscal a nivel CONTRIBUYENTE (1:1 con client). SIN direccion/
-- establecimiento/punto (eso vive por establecimiento). Aqui van tipo de contribuyente,
-- regimen y nombre de fantasia. La direccion/geo del DE la aporta el establecimiento.
CREATE TABLE client_emisor (
  id_client_emisor   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id          NUMBER NOT NULL,
  tipo_contribuyente NUMBER(1) NOT NULL,               -- iTipCont (1 fisica, 2 juridica)
  tipo_regimen       NUMBER(2),                        -- cTipReg
  nombre_fantasia    VARCHAR2(255),
  CONSTRAINT fk_client_emisor_client FOREIGN KEY (client_id) REFERENCES client (id_client) ON DELETE CASCADE,
  CONSTRAINT uq_client_emisor        UNIQUE (client_id)
);

COMMENT ON TABLE client_emisor IS 'Identidad fiscal a nivel contribuyente (1:1 con client). Sin direccion/est/punto.';
