-- client_emisor_actividad: actividades economicas del contribuyente (1:N). Cada una es
-- un par cActEco/dDesActEco. La descripcion debe ser EXACTA con acentos/puntuacion o SIFEN
-- rechaza con 1261/1262 (validado: 74909 = "OTRAS ACTIVIDADES PROFESIONALES...").
CREATE TABLE client_emisor_actividad (
  id_actividad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id    NUMBER NOT NULL,
  cod_act_eco  VARCHAR2(20)  NOT NULL,                 -- cActEco
  desc_act_eco VARCHAR2(300) NOT NULL,                 -- dDesActEco (exacta)
  is_active    NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT fk_actividad_client FOREIGN KEY (client_id) REFERENCES client (id_client) ON DELETE CASCADE,
  CONSTRAINT uq_actividad        UNIQUE (client_id, cod_act_eco),
  CONSTRAINT ck_actividad_active CHECK (is_active IN (0,1))
);

COMMENT ON TABLE client_emisor_actividad IS 'Actividades economicas del contribuyente (cActEco/dDesActEco). Descripcion EXACTA o error 1261/1262.';
