-- client_establecimiento: sucursal (1:N por client). Cada establecimiento tiene SU propia
-- direccion y geo (dep/dis/ciu), porque dDirEmi (D107) es "la direccion del local donde se
-- emite el DE" y cDepEmi/cDisEmi/cCiuEmi (D111/D113/D115) son de ese local, NO de casa matriz.
-- La geo debe coincidir con la registrada en el RUC/SET o SIFEN rechaza con 1255.
CREATE TABLE client_establecimiento (
  id_establecimiento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id          NUMBER NOT NULL,
  codigo             VARCHAR2(3) NOT NULL,             -- dEst: '001', '002', ...
  denominacion       VARCHAR2(255),                    -- dDenSuc (denominacion de la sucursal)
  direccion          VARCHAR2(255) NOT NULL,           -- dDirEmi
  num_casa           VARCHAR2(6) DEFAULT '0',          -- dNumCas
  dep_cod            NUMBER NOT NULL,                  -- cDepEmi
  dep_desc           VARCHAR2(60) NOT NULL,            -- dDesDepEmi
  dis_cod            NUMBER,                           -- cDisEmi
  dis_desc           VARCHAR2(60),                     -- dDesDisEmi
  ciu_cod            NUMBER NOT NULL,                  -- cCiuEmi
  ciu_desc           VARCHAR2(60) NOT NULL,            -- dDesCiuEmi
  telefono           VARCHAR2(20),
  email              VARCHAR2(150),
  is_active          NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT fk_estab_client FOREIGN KEY (client_id) REFERENCES client (id_client) ON DELETE CASCADE,
  CONSTRAINT uq_establecimiento UNIQUE (client_id, codigo),
  CONSTRAINT ck_estab_active    CHECK (is_active IN (0,1))
);

COMMENT ON TABLE client_establecimiento IS 'Sucursal (1:N por client) con su direccion/geo propia (dDirEmi/cDepEmi...). Geo debe coincidir con el RUC/SET (o error 1255).';
