-- client_punto_expedicion: punto de expedicion / caja (1:N por establecimiento).
-- client_id se desnormaliza para que la VPD por client_id aplique directo sobre esta tabla.
CREATE TABLE client_punto_expedicion (
  id_punto           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  establecimiento_id NUMBER NOT NULL,
  client_id          NUMBER NOT NULL,                  -- desnormalizado para la VPD
  codigo             VARCHAR2(3) NOT NULL,             -- dPunExp: '001', '002', ...
  descripcion        VARCHAR2(255),
  is_active          NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT fk_punto_estab  FOREIGN KEY (establecimiento_id) REFERENCES client_establecimiento (id_establecimiento) ON DELETE CASCADE,
  CONSTRAINT fk_punto_client FOREIGN KEY (client_id) REFERENCES client (id_client) ON DELETE CASCADE,
  CONSTRAINT uq_punto        UNIQUE (establecimiento_id, codigo),
  CONSTRAINT ck_punto_active CHECK (is_active IN (0,1))
);

CREATE INDEX ix_punto_client ON client_punto_expedicion (client_id);

COMMENT ON TABLE client_punto_expedicion IS 'Punto de expedicion / caja (1:N por establecimiento). dPunExp.';
