-- client_sifen_env: timbrado + CSC por AMBIENTE (TEST / PROD). El CSC se guarda cifrado
-- igual que el certificado (AES-256-GCM hecho en Go). El ambiente lo determina el prefijo de
-- la API key (sk_test_ -> TEST, sk_prod_ -> PROD); Go elige la fila segun ese prefijo.
CREATE TABLE client_sifen_env (
  id_sifen_env          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id             NUMBER NOT NULL,
  environment           VARCHAR2(4) NOT NULL,           -- TEST | PROD
  num_timbrado          VARCHAR2(8) NOT NULL,           -- dNumTim (8 digitos, con pad)
  fecha_inicio_vigencia DATE NOT NULL,                  -- dFeIniT
  id_csc                VARCHAR2(4) NOT NULL,           -- idCSC
  csc_ciphertext        BLOB NOT NULL,                  -- CSC cifrado (Go)
  csc_nonce             RAW(16) NOT NULL,
  key_version           NUMBER DEFAULT 1,
  is_active             NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT fk_sifen_env_client FOREIGN KEY (client_id) REFERENCES client (id_client) ON DELETE CASCADE,
  CONSTRAINT uq_client_env       UNIQUE (client_id, environment),
  CONSTRAINT ck_sifen_env_name   CHECK (environment IN ('TEST','PROD')),
  CONSTRAINT ck_sifen_env_active CHECK (is_active IN (0,1))
);

COMMENT ON TABLE client_sifen_env IS 'Timbrado + CSC (cifrado) por ambiente TEST/PROD. Ambiente lo determina el prefijo de la API key.';
