-- document_sequence: correlativo por (client, ambiente, establecimiento, punto, tipo DE).
-- El numero de documento se asigna secuencialmente y sin huecos. Go pide el proximo numero
-- con bloqueo (UPDATE ... RETURNING) via endpoint interno, reemplazando el numDoc "demo".
CREATE TABLE document_sequence (
  id_document_sequence NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id            NUMBER NOT NULL,
  environment          VARCHAR2(4)  NOT NULL,           -- TEST | PROD
  establecimiento      VARCHAR2(3)  NOT NULL,
  punto_expedicion     VARCHAR2(3)  NOT NULL,
  tipo_de              NUMBER NOT NULL,                 -- 1 FE, 4 auto, 5 NCE, 6 NDE, 7 NR
  last_number          NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT fk_doc_seq_client FOREIGN KEY (client_id) REFERENCES client (id_client) ON DELETE CASCADE,
  CONSTRAINT uq_doc_seq        UNIQUE (client_id, environment, establecimiento, punto_expedicion, tipo_de),
  CONSTRAINT ck_doc_seq_env    CHECK (environment IN ('TEST','PROD'))
);

COMMENT ON TABLE document_sequence IS 'Correlativo sin huecos por (client, ambiente, establecimiento, punto, tipo DE). Se incrementa con bloqueo.';
