-- document: cabecera de cada DE emitido (para el panel futuro). Estados canonicos:
-- BORRADOR -> FIRMADO -> ENVIADO -> APROBADO | RECHAZADO, y CANCELADO via evento.
CREATE TABLE document (
  id_document      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id        NUMBER NOT NULL,
  environment      VARCHAR2(4) NOT NULL,               -- TEST | PROD
  tipo_de          NUMBER NOT NULL,                    -- 1 FE, 4 auto, 5 NCE, 6 NDE, 7 NR
  cdc              VARCHAR2(44),
  num_documento    VARCHAR2(7),
  establecimiento  VARCHAR2(3),
  punto_expedicion VARCHAR2(3),
  receptor_nombre  VARCHAR2(255),
  receptor_doc     VARCHAR2(20),
  moneda           VARCHAR2(3),
  total_operacion  NUMBER,
  estado           VARCHAR2(20) NOT NULL,              -- BORRADOR|FIRMADO|ENVIADO|APROBADO|RECHAZADO|CANCELADO
  cod_res          VARCHAR2(10),
  prot_aut         VARCHAR2(30),
  mensaje_res      VARCHAR2(1000),
  fecha_emision    TIMESTAMP(6) WITH TIME ZONE,
  -- Reenvio de FIRMADO (fallo transitorio de envio a SET): el panel marca retry_requested
  -- y un worker en Go reenvia el XML firmado. Ver PKG_ESIGN_DOCUMENT_API.pr_request_retry.
  retry_requested  NUMBER(1) DEFAULT 0 NOT NULL,
  retry_count      NUMBER DEFAULT 0 NOT NULL,
  last_retry_at    TIMESTAMP(6) WITH TIME ZONE,
  recovery_required NUMBER(1) DEFAULT 0 NOT NULL,
  recovery_reason   VARCHAR2(500),
  recovery_marked_at TIMESTAMP(6) WITH TIME ZONE,
  idempotency_key  VARCHAR2(128),
  created_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_document_client FOREIGN KEY (client_id) REFERENCES client (id_client),
  CONSTRAINT uq_document_cdc    UNIQUE (cdc),
  CONSTRAINT ck_document_env    CHECK (environment IN ('TEST','PROD')),
  CONSTRAINT ck_document_estado CHECK (estado IN ('BORRADOR','FIRMADO','ENVIADO','APROBADO','RECHAZADO','CANCELADO')),
  CONSTRAINT ck_document_recovery_required CHECK (recovery_required IN (0, 1))
);

CREATE INDEX ix_document_client_env ON document (client_id, environment);
CREATE INDEX ix_document_estado     ON document (client_id, estado);
CREATE UNIQUE INDEX uq_document_idempotency
  ON document (
    CASE WHEN idempotency_key IS NOT NULL THEN client_id END,
    CASE WHEN idempotency_key IS NOT NULL THEN environment END,
    idempotency_key
  );

COMMENT ON TABLE document IS 'Cabecera de cada DE emitido. Estado: BORRADOR->FIRMADO->ENVIADO->APROBADO|RECHAZADO, CANCELADO via evento.';
