-- document_event: eventos sobre documentos (cancelacion / inutilizacion).
-- La inutilizacion puede no tener document_id (es sobre un rango de numeros, no un DE emitido).
CREATE TABLE document_event (
  id_document_event NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id       NUMBER,
  client_id         NUMBER NOT NULL,
  tipo_evento       VARCHAR2(20) NOT NULL,             -- CANCELACION | INUTILIZACION
  estado            VARCHAR2(20),
  cod_res           VARCHAR2(10),
  prot_aut          VARCHAR2(30),
  motivo            VARCHAR2(500),
  created_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_doc_event_doc    FOREIGN KEY (document_id) REFERENCES document (id_document),
  CONSTRAINT fk_doc_event_client FOREIGN KEY (client_id)   REFERENCES client (id_client),
  CONSTRAINT ck_doc_event_tipo   CHECK (tipo_evento IN ('CANCELACION','INUTILIZACION'))
);

CREATE INDEX ix_doc_event_client ON document_event (client_id);

COMMENT ON TABLE document_event IS 'Eventos SIFEN: CANCELACION (sobre un DE) | INUTILIZACION (sobre un rango de numeros).';
