-- api_log: bitacora de llamadas a la API (para observabilidad del panel). client_id puede
-- ser NULL cuando la request falla antes de resolver el tenant (p. ej. API key invalida).
CREATE TABLE api_log (
  id_api_log  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id   NUMBER,
  environment VARCHAR2(4),
  endpoint    VARCHAR2(200),
  http_status NUMBER,
  latency_ms  NUMBER,
  created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX ix_api_log_client ON api_log (client_id, created_at);

COMMENT ON TABLE api_log IS 'Bitacora de llamadas a la API. client_id NULL si aun no se resolvio el tenant.';
