-- client_api_key: API keys rotables por ambiente (patron Stripe, tabla hija de client).
-- Promueve las columnas sk_test_*/sk_prod_* de client a un historial: se pueden rotar y
-- coexistir varias keys ACTIVE por ambiente. Se guarda HASH + prefijo (nunca la key en claro).
-- El ambiente lo determina el prefijo (sk_test_/sk_prod_); pr_resolve_key busca por hash.
CREATE TABLE client_api_key (
  id_client_api_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id   NUMBER NOT NULL REFERENCES client ON DELETE CASCADE,
  environment VARCHAR2(4)   NOT NULL,                  -- TEST | PROD
  prefix      VARCHAR2(24)  NOT NULL,                  -- p.ej. sk_test_a1b2 (visible)
  key_hash    VARCHAR2(128) NOT NULL,                  -- SHA-256 de la key completa
  label       VARCHAR2(100),                           -- etiqueta opcional (ej. "CI/CD")
  status      VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,  -- ACTIVE | REVOKED
  created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  revoked_at  TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT uq_client_api_key_hash UNIQUE (key_hash),
  CONSTRAINT ck_client_api_key_env    CHECK (environment IN ('TEST','PROD')),
  CONSTRAINT ck_client_api_key_status CHECK (status IN ('ACTIVE','REVOKED'))
);

CREATE INDEX ix_client_api_key_client ON client_api_key (client_id, environment, status);

COMMENT ON TABLE  client_api_key IS 'API keys rotables por ambiente (hija de client). Historial: keys REVOKED se conservan.';
COMMENT ON COLUMN client_api_key.key_hash IS 'SHA-256 de la key completa. La key en claro se muestra 1 sola vez al crearse.';
