-- client_certificate: certificados .p12 del cliente (tabla hija de client). Promueve las
-- columnas cert_* de client a un historial con varios certificados; a lo sumo uno ACTIVE.
-- Siempre cifrados por Go (AES-256-GCM): Oracle solo ve ciphertext + nonce, nunca el claro.
CREATE TABLE client_certificate (
  id_client_certificate NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id       NUMBER NOT NULL REFERENCES client ON DELETE CASCADE,
  subject_dn      VARCHAR2(400),
  not_after       TIMESTAMP(6) WITH TIME ZONE,
  p12_ciphertext  BLOB    NOT NULL,
  p12_nonce       RAW(16) NOT NULL,
  pwd_ciphertext  BLOB    NOT NULL,
  pwd_nonce       RAW(16) NOT NULL,
  key_version     NUMBER DEFAULT 1 NOT NULL,           -- version de la clave maestra (rotacion)
  status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,  -- ACTIVE | INACTIVE | EXPIRED
  created_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT ck_client_cert_status CHECK (status IN ('ACTIVE','INACTIVE','EXPIRED'))
);

CREATE INDEX ix_client_cert_client ON client_certificate (client_id, status);

COMMENT ON TABLE  client_certificate IS 'Certificados .p12 del cliente (hija de client). A lo sumo uno ACTIVE; el resto queda INACTIVE.';
COMMENT ON COLUMN client_certificate.p12_ciphertext IS 'P12 cifrado AES-256-GCM (clave maestra en Go). Oracle nunca ve el claro.';
