-- client_invitation: invitaciones por token (owner invita a un email a su negocio con un rol).
-- Si el invitado aun no tiene usuario, se crea una invitacion PENDING con token + expiracion;
-- al aceptarla (pr_accept_invitation) se crea el usuario y su membresia con el rol asignado.
CREATE TABLE client_invitation (
  id_client_invitation NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id   NUMBER NOT NULL REFERENCES client ON DELETE CASCADE,
  email       VARCHAR2(150) NOT NULL,
  role        VARCHAR2(20)  NOT NULL,
  token       VARCHAR2(80)  NOT NULL,
  status      VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,  -- PENDING | ACCEPTED | REVOKED | EXPIRED
  expires_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  accepted_at TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT uq_client_invitation_token UNIQUE (token),
  CONSTRAINT ck_client_invitation_role   CHECK (role IN ('owner','developer','analyst')),
  CONSTRAINT ck_client_invitation_status CHECK (status IN ('PENDING','ACCEPTED','REVOKED','EXPIRED'))
);

CREATE INDEX ix_client_invitation_email ON client_invitation (email, status);

COMMENT ON TABLE client_invitation IS 'Invitaciones por token (owner -> email + rol). Al aceptarse crea usuario + membresia.';
