-- document_kude_task: cola durable de generación de KuDE (PDF).
-- Sustituye la goroutine suelta de la request HTTP: PENDING → PROCESSING (lease) → READY|FAILED.
-- El payload_json es el KudeData serializado (inmutable, seguro entre workers).
CREATE TABLE document_kude_task (
  id_task       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id     NUMBER NOT NULL,
  document_id   NUMBER NOT NULL,
  cdc           VARCHAR2(44) NOT NULL,
  status        VARCHAR2(20) NOT NULL,
  attempts      NUMBER DEFAULT 0 NOT NULL,
  max_attempts  NUMBER DEFAULT 10 NOT NULL,
  lease_owner   VARCHAR2(64),
  lease_until   TIMESTAMP(6) WITH TIME ZONE,
  payload_json  CLOB,
  last_error    VARCHAR2(2000),
  created_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  completed_at  TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT fk_kude_task_client FOREIGN KEY (client_id) REFERENCES client (id_client) ON DELETE CASCADE,
  CONSTRAINT fk_kude_task_doc    FOREIGN KEY (document_id) REFERENCES document (id_document) ON DELETE CASCADE,
  CONSTRAINT uq_kude_task_doc    UNIQUE (document_id),
  CONSTRAINT ck_kude_task_status CHECK (status IN ('PENDING', 'PROCESSING', 'READY', 'FAILED'))
);

CREATE INDEX ix_kude_task_claim ON document_kude_task (status, lease_until, created_at);
CREATE INDEX ix_kude_task_cdc   ON document_kude_task (client_id, cdc);

COMMENT ON TABLE document_kude_task IS 'Cola durable KuDE: lease + intentos; payload = KudeData JSON. XML no se publica en bucket.';
