-- document_webhook_delivery: cola durable de POST webhook (invoice.ready).
-- PENDING → PROCESSING (lease) → DELIVERED | FAILED.
CREATE TABLE document_webhook_delivery (
  id_delivery      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id        NUMBER NOT NULL,
  document_id      NUMBER NOT NULL,
  cdc              VARCHAR2(44) NOT NULL,
  environment      VARCHAR2(4) NOT NULL,
  event_type       VARCHAR2(40) NOT NULL,
  event_id         VARCHAR2(80) NOT NULL,
  delivery_uuid    VARCHAR2(64) NOT NULL,
  target_url       VARCHAR2(500),
  status           VARCHAR2(20) NOT NULL,
  attempts         NUMBER DEFAULT 0 NOT NULL,
  max_attempts     NUMBER DEFAULT 10 NOT NULL,
  lease_owner      VARCHAR2(64),
  lease_until      TIMESTAMP(6) WITH TIME ZONE,
  last_http_status NUMBER,
  last_error       VARCHAR2(2000),
  delivered_at     TIMESTAMP(6) WITH TIME ZONE,
  created_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_whd_client FOREIGN KEY (client_id) REFERENCES client (id_client) ON DELETE CASCADE,
  CONSTRAINT fk_whd_doc FOREIGN KEY (document_id) REFERENCES document (id_document) ON DELETE CASCADE,
  CONSTRAINT uq_whd_doc_event UNIQUE (document_id, event_type),
  CONSTRAINT uq_whd_event_id UNIQUE (event_id),
  CONSTRAINT uq_whd_delivery_uuid UNIQUE (delivery_uuid),
  CONSTRAINT ck_whd_env CHECK (environment IN ('TEST', 'PROD')),
  CONSTRAINT ck_whd_status CHECK (status IN ('PENDING', 'PROCESSING', 'DELIVERED', 'FAILED'))
);

CREATE INDEX ix_whd_claim ON document_webhook_delivery (status, lease_until, created_at);
CREATE INDEX ix_whd_client_cdc ON document_webhook_delivery (client_id, cdc);

COMMENT ON TABLE document_webhook_delivery IS 'Cola durable de webhooks salientes (invoice.ready). Worker Go reclama con lease y POSTea HMAC.';
COMMENT ON COLUMN document_webhook_delivery.event_id IS 'Idempotencia del evento (ej. document.invoice.ready.{cdc}).';
COMMENT ON COLUMN document_webhook_delivery.delivery_uuid IS 'UUID estable por intento de entrega (header X-Esign-Delivery-Id).';
